server {
  listen 80;
  server_name _;
  client_max_body_size 10m;


  location /static/ {
    alias /var/www/sisu2/static/;
  }
  location /media/ {
    alias /var/www/sisu2/media/;
  }


  location / {
    proxy_set_header Host $host;
    proxy_pass http://unix:/tmp/gunicorn_sisu2.sock;
  }

}
