# Generated by Django 4.2.4 on 2023-09-08 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TopMenu',
            fields=[
                ('url', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('order', models.IntegerField()),
            ],
            options={
                'db_table': 't_top_menu',
                'db_table_comment': '최상위 메뉴',
                'managed': True,
            },
        ),
    ]
