# Generated by Django 4.2.4 on 2023-10-31 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_alter_profile_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TopMenu',
        ),
    ]
