# Generated by Django 4.2.4 on 2023-09-22 04:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('seq', models.IntegerField()),
                ('id_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomment', to='blog.menu')),
            ],
            options={
                'db_table': 't_blog_menu',
                'db_table_comment': '블로그 메뉴',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('views', models.IntegerField()),
                ('visible', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('insert_ip', models.CharField(max_length=40)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_ip', models.CharField(blank=True, max_length=40, null=True)),
                ('menu', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blog.menu')),
            ],
            options={
                'db_table': 't_post',
                'db_table_comment': '블로그 게시글',
                'managed': True,
            },
        ),
    ]
