# Generated by Django 4.2.4 on 2023-09-18 06:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=20)),
                ('seq', models.IntegerField()),
                ('id_parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recomment', to='blog.menu')),
            ],
            options={
                'db_table': 't_blog_menu',
                'db_table_comment': '블로그 메뉴',
                'managed': True,
            },
        ),
    ]
