# Generated by Django 4.2.4 on 2023-10-31 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BlogTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('seq', models.IntegerField()),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree', to='blog.blogtree')),
            ],
            options={
                'db_table': 't_blog_tree',
                'db_table_comment': '블로그 트리 메뉴',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('thumbnail', models.CharField(max_length=100, null=True)),
                ('is_public', models.BooleanField()),
                ('insert_date', models.DateTimeField()),
                ('insert_ip', models.CharField(max_length=40)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_ip', models.CharField(blank=True, max_length=40, null=True)),
                ('view_count', models.IntegerField(default=0)),
                ('tree', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='post', to='blog.blogtree')),
            ],
            options={
                'db_table': 't_blog_post',
                'db_table_comment': '블로그 게시글',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authenticated', models.BooleanField()),
                ('nickname', models.CharField(max_length=12)),
                ('password', models.CharField(max_length=128)),
                ('content', models.CharField(max_length=400)),
                ('insert_date', models.DateTimeField()),
                ('insert_ip', models.CharField(max_length=40)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.blogpost')),
            ],
            options={
                'db_table': 't_blog_comment',
                'db_table_comment': '블로그 댓글',
                'managed': True,
            },
        ),
    ]
