# Generated by Django 4.2.4 on 2023-10-18 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_rename_visible_blogpost_is_public_blogpost_thumbnail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
