# Generated by Django 4.2.4 on 2023-10-18 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_blogpost_view_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogtree',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tree', to='blog.blogtree'),
        ),
    ]
