# Generated by Django 4.2.4 on 2023-10-19 01:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_alter_blogtree_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_authenticated', models.BooleanField()),
                ('nickname', models.CharField(max_length=10)),
                ('password', models.CharField(blank=True, max_length=2, null=True)),
                ('content', models.CharField(max_length=10)),
                ('insert_date', models.DateTimeField()),
                ('insert_ip', models.CharField(max_length=40)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='blog.blogpost')),
            ],
            options={
                'db_table': 't_blog_comment',
                'db_table_comment': '블로그 댓글',
                'managed': True,
            },
        ),
    ]
