# Generated by Django 4.2.4 on 2023-10-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blogcomment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomment',
            name='content',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='nickname',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
