# Generated by Django 4.2.4 on 2023-10-30 01:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_blogcomment_hashed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogcomment',
            name='hashed',
        ),
        migrations.AlterField(
            model_name='blogcomment',
            name='password',
            field=models.CharField(default=django.utils.timezone.now, max_length=128),
            preserve_default=False,
        ),
    ]
