# Generated by Django 4.2.4 on 2023-10-31 05:24

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('title_en', models.CharField(max_length=100)),
                ('brand', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('format', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('weekday', models.IntegerField()),
                ('poster', models.ImageField(upload_to=common.utils.ImageUpload('poster'))),
                ('thumbnail', models.ImageField(upload_to=common.utils.ImageUpload('thumbnail'))),
                ('insert_date', models.DateTimeField()),
                ('insert_ip', models.CharField(max_length=40)),
                ('update_date', models.DateTimeField(blank=True, null=True)),
                ('update_ip', models.CharField(blank=True, max_length=40, null=True)),
            ],
            options={
                'db_table': 't_movie',
                'db_table_comment': '영화 기록',
                'managed': True,
            },
        ),
    ]
