# Generated by Django 4.2.4 on 2023-08-30 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='modify_date',
            new_name='update_date',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='modify_ip',
            new_name='update_ip',
        ),
    ]
