# Generated by Django 4.2.4 on 2023-11-06 05:21

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(max_length=250, upload_to=common.utils.ImageUpload('poster')),
        ),
    ]
