# Generated by Django 4.2.4 on 2023-08-30 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_rename_modify_date_movie_update_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='weekday',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
