# Generated by Django 4.2.4 on 2023-09-05 07:46

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0004_movie_poster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.ImageField(upload_to=common.utils.ImageUpload('poster')),
        ),
    ]
