# Generated by Django 4.2.4 on 2023-09-07 04:33

import common.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0005_alter_movie_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='thumbnail',
            field=models.ImageField(default='test', upload_to=common.utils.ImageUpload('thumbnail')),
            preserve_default=False,
        ),
    ]
